### ISSUE TITLE
Work with multiple cursors

### ISSUE THREAD

**Issue by 1shkoda1** [tonyrapozo/System.Data.OracleClient#3]
It is impossible to read several cursors. Because after read first cursor flags 'hasRows'. false. And next cursor doesn`t read.
Problem in OracleDataReader.cs line 772. Maybe need reset 'hasRows'.
Example:

    using (var cmd = dbConnection.CreateCommand())
                {
                    cmd.CommandText = "BEGIN  " +
                                                "OPEN :p_1 FOR SELECT * FROM user_tables WHERE rownum < 3;" +
                                                "OPEN :p_2 FOR SELECT * FROM user_tables WHERE rownum  < 3; " +
                                                "END;";

                    cmd.Parameters.Add(
                            new OracleParameter("p_1", OracleType.Cursor) {Direction = ParameterDirection.Output}
                        ) ;
                    cmd.Parameters.Add(
                            new OracleParameter("p_2", OracleType.Cursor) { Direction = ParameterDirection.Output }
                        ) ;

                    int res = 0;
                    var rdr = cmd.ExecuteReader();
                    while (rdr.Read())
                    {
                        res++;
                    }

                    rdr.NextResult();

                    // HasRows == false
                    // Second cursor fetching failed
                    while (rdr.Read())
                    {
                        res++;
                    }

                    rdr.Close();
                    return res;
                }

**Comment by jirsak-ondrej** [comment]
I just created pull request for this issue

https://github.com/tonyrapozo/System.Data.OracleClient/pull/4

**Comment by tonyrapozo** [comment]
Merged: [32824fddb3140942d6fe7faee1a1279d0d48d68a](https://github.com/tonyrapozo/System.Data.OracleClient/commit/32824fddb3140942d6fe7faee1a1279d0d48d68a)
